[package]
edition = "2021"
name = "smartknob-rs"
version = "0.1.0"

[[bin]]
name = "smartknob-rs"
path = "./src/bin/main.rs"

[dependencies]
critical-section = "1.2.0"
embassy-embedded-hal = "0.3.0"
embassy-executor = { version = "0.7.0", features = ["task-arena-size-20480"] }
embassy-sync = "0.6.2"
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
esp-alloc = "0.7.0"
esp-backtrace = { version = "0.15.1", features = [
  "esp32s3",
  "exception-handler",
  "panic-handler",
  "println",
] }
esp-hal = { version = "1.0.0-beta.0", features = ["esp32s3", "unstable"] }
esp-hal-embassy = { version = "0.7.0", features = ["esp32s3"] }
esp-hal-smartled = { git = "https://github.com/robamu/esp-hal-community", rev = "309f19e", features = [
  "esp32s3",
] }
esp-println = { version = "0.13.0", features = ["esp32s3", "log"] }
foc = "0.3.0"
log = { version = "0.4.21" }
smart-leds = "0.4.0"
static_cell = { version = "2.1.0", features = ["nightly"] }
mt6701 = { path = "../mt6701" }
ldc1x1x = { path = "../ldc1x1x" }
nalgebra = { version = "0.33.2", default-features = false, features = [
  "macros",
  "nalgebra-macros",
  "libm",
] }
heapless = "0.8.0"
average = "0.16.0"
libm = "0.2.13"
fixed = "1.29.0"
embassy-usb = "0.4.0"
menu = { path = "../menu", features = ["noline"] }
embedded-io-async = "0.6.1"
embassy-futures = "0.1.1"
noline = "0.5.1"
embedded-io = "0.6.1"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
