[package]
edition = "2021"
name = "smartknob-rs"
version = "0.1.0"

[[bin]]
name = "smartknob-rs"
path = "./src/bin/main.rs"

[dependencies]
critical-section = "1.2.0"
embassy-embedded-hal = "0.3.0"
embassy-executor = { version = "0.7.0", features = ["task-arena-size-20480"] }
embassy-sync = "0.6.2"
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
esp-alloc = "0.7.0"
esp-backtrace = { version = "0.15.1", features = [
  "esp32s3",
  "exception-handler",
  "panic-handler",
  "println",
] }
esp-hal = { version = "1.0.0-beta.0", features = ["esp32s3", "unstable"] }
esp-hal-embassy = { version = "0.7.0", features = ["esp32s3"] }
esp-hal-smartled = { git = "https://github.com/esp-rs/esp-hal-community", rev = "a613668", features = [
  "esp32s3",
] }
esp-println = { version = "0.13.0", features = ["esp32s3", "log"] }
foc = "0.3.0"
log = { version = "0.4.21" }
smart-leds = "0.4.0"
static_cell = { version = "2.1.0", features = ["nightly"] }
mt6701 = { path = "../mt6701" }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
