[package]
edition = "2021"
name = "smartknob-rs"
version = "0.1.0"

[[bin]]
name = "smartknob-rs"
path = "./src/bin/main.rs"

[dependencies]
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal.git", rev = "0267f7c", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal.git", rev = "0267f7c", features = [
  "esp32s3",
] }
esp-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "0267f7c", features = [
  "esp32s3",
  "log-04",
  "unstable",
] }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal.git", rev = "0267f7c", default-features = false, features = [
  "esp32s3",
  "embassy",
  "log-04",
] }
esp-println = { git = "https://github.com/esp-rs/esp-hal.git", rev = "0267f7c", features = [
  "esp32s3",
  "log-04",
] }
embassy-embedded-hal = "0.5.0"
embassy-executor = { version = "0.9.0", features = ["log"] }
embassy-sync = "0.7.0"
embassy-time = "0.5.0"
esp-alloc = "0.8.0"
critical-section = "1.2.0"
esp-hal-smartled = { path="../esp-hal-community/esp-hal-smartled", features = [
  "esp32s3",
] }
foc = "0.3.0"
log = "0.4.27"
smart-leds = "0.4.0"
static_cell = { version = "2.1.1", features = ["nightly"] }
mt6701 = { path = "../mt6701" }
ldc1x1x = { path = "../ldc1x1x" }
nalgebra = { version = "0.34.1", default-features = false, features = [
  "macros",
  "nalgebra-macros",
  "libm",
] }
average = "0.16.0"
libm = "0.2.13"
fixed = "1.29.0"
embassy-usb = "0.5.1"
embedded-io-async = "0.7.0"
ufmt = "0.2.0"
embedded-cli = "0.2.1"

# [replace]
# "esp-hal:1.0.0-rc.0" = { git = "https://github.com/esp-rs/esp-hal.git", rev = "0267f7c" }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
