[target.xtensa-esp32s3-none-elf]
rustflags = ["-C", "link-arg=-nostartfiles", "-Z", "stack-protector=all"]

[env]
ESP_LOG = "info"
ESP_HAL_CONFIG_PSRAM_MODE = "octal"

[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
